config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  draw(:sessions)

  root to: "meetings#index"
  resources :meetings
  resources :users, except: :create
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  authenticates_with_sorcery!

  MIN_PASSWORD_LENGTH = 6
  validates :password, presence: true, length: {minimum: MIN_PASSWORD_LENGTH}, confirmation: true
  validates :password_confirmation, presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/meeting.rb
# frozen_string_literal: true

class Meeting < ApplicationRecord
  before_save :set_finished_at

  has_one_attached :preview_image

  validates :title, :description, :address, :started_at, :duration,
    presence: true
  validates :participants_limit, numericality: {greater_than: 0}, allow_nil: true

  def set_finished_at
    self.finished_at = started_at + duration.minutes
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery!

  enum gender: [:male, :female]

  MIN_PASSWORD_LENGTH = 6
  validates :password, presence: true, length: {minimum: MIN_PASSWORD_LENGTH}, confirmation: true
  validates :password_confirmation, presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to welcome_path
  end
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[show edit update destroy]

  def index
    @meetings = Meeting.order(:id)
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    if @meeting.save
      redirect_to meetings_path
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @meeting.update(meeting_params)
      @meeting.preview_image.attach(image_from_params) if image_from_params
      redirect_to meetings_path
    else
      render "edit"
    end
  end

  def destroy
    @meeting.delete
    redirect_to meetings_path
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def image_from_params
    params[:meeting][:preview_image]
  end

  def meeting_params
    params.require(:meeting).permit(:title, :description, :address, :started_at,
      :duration, :latitude, :longitude, :participants_limit)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :require_login

  def new
    @user = User.new
  end

  def register
    user = User.new(*user_params)
    return redirect_to sign_up_path, notice: t("user_not_created") unless user.valid?

    user.save
    auto_login(user)
    redirect_to meetings_path
  end

  def sign_in
  end

  def authorize
    email = user_params[:email]
    password = user_params[:password]
    return redirect_to meetings_path if login(email, password)

    redirect_to sign_in_path, notice: t("user_not_exist")
  end

  def welcome
  end

  def destroy
    logout
    redirect_to welcome_path
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metoo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
    <script src="https://api-maps.yandex.ru/2.1/?apikey=59d0c9b1-9769-4e2d-b1fa-e751b6998a02&lang=ru_RU&load=Geolink"
            type="text/javascript"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meetings/edit.html.erb
<h1><%= t('to_edit') %></h1>

<%= simple_form_for @meeting, url: meeting_path(@meeting.id), wrapper: :horizontal_form,
                    wrapper_mappings: {
                      datetime:      :horizontal_multi_select,
                      range:         :horizontal_range
                    } do |m| %>
  <div class="row mb-4">
    <%= m.input :title, class: 'mb-4', required: true %>
  </div>

  <div class="row mb-4">
    <%= m.input :description, required: true %>
  </div>

  <div class="row mb-4">
    <%= m.input :preview_image, wrapper_html: { class: 'col-3' } %>

    <div class="col-9">
      <% if @meeting.preview_image.attached? %>
        <%= image_tag @meeting.preview_image, size: 50  %>
      <% end %>
    </div>
  </div>

  <div class="row mb-4">
    <%= m.input :participants_limit, class: 'mb-4', input_html: { min: 1 } %>
  </div>

  <div class="row mb-4">
    <%= m.input :latitude, as: :hidden, input_html: { id: 'addr-lat' }  %>
    <%= m.input :longitude, as: :hidden, input_html: { id: 'addr-long' }  %>
    <%= m.input :address, required: true, input_html: { id: 'addr-suggestions' } %>
  </div>

  <div class="row mb-4">
    <div class="col">
      <%= m.input :started_at, required: true, as: :string,
                  input_html: {
                    class: 'datetimerange',
                    value: @meeting.started_at.strftime('%d/%m/%Y %H:%M')
                  },
                  start_year: Date.today.year %>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col">
      <%= m.input :duration, required: true, input_html: { min: 60, max: 1440, step: 5 } %>
    </div>
  </div>

  <%= m.button :submit, class: 'btn-primary' %>
<% end %>

app/views/meetings/index.html.erb
<%= render partial: "partials/profile_links" %>

<h1><%= t('meetings') %></h1>

<%= link_to t('create_meeting'), new_meeting_path %>

<div class="row mt-5">
  <% @meetings.each do |m| %>
    <div class="col">
      <h4><%= m.title %></h4>

      <% if m.preview_image.attached? %>
        <div class="mt-4 mb-4">
          <%= image_tag m.preview_image, size: 300 %>
        </div>
      <% end %>

      <p><%= m.description %></p>
      <% if m.participants_limit %>
        <%= content_tag :div, "#{t('participants_amount')}: #{m.participants_limit}", class: 'mb-3' %>
      <% end %>

      <address>
        <b class="ymaps-geolink">
          <%= m.address %>
        </b>
      </address>

      <div>
        <%= time_tag m.started_at %>
        &nbsp;-
        <%= time_tag m.finished_at %>
      </div>

      <div>
        <%= link_to t('to_edit'), edit_meeting_path(m.id) %>
        <%= link_to t('more_link'), meeting_path(m.id), class: 'link-dark' %>
        <%= link_to t('to_delete'), meeting_path(m.id),
                    data: {:confirm => t('sure?')},
                    method: :delete, class: 'link-danger' %>
      </div>
    </div>
  <% end %>
</div>

app/views/meetings/new.html.erb
<h1><%= t('create_meeting') %></h1>

<%= simple_form_for @meeting, url: meetings_path, wrapper: :horizontal_form,
    wrapper_mappings: {
      datetime:      :horizontal_multi_select,
      range:         :horizontal_range
    } do |m| %>
  <div class="row mb-4">
    <%= m.input :title, class: 'mb-4', required: true %>
  </div>

  <div class="row mb-4">
    <%= m.input :description, required: true %>
  </div>

  <div class="row mb-4">
    <%= m.input :preview_image, class: 'mb-4' %>
  </div>

  <div class="row mb-4">
    <%= m.input :participants_limit, class: 'mb-4', input_html: { min: 1 } %>
  </div>

  <div class="row mb-4">
    <%= m.input :latitude, as: :hidden, input_html: { id: 'addr-lat' }  %>
    <%= m.input :longitude, as: :hidden, input_html: { id: 'addr-long' }  %>
    <%= m.input :address, required: true, input_html: { id: 'addr-suggestions' } %>
  </div>

  <div class="row mb-4">
    <div class="col">
      <%= m.input :started_at, required: true,
                  input_html: { class: 'datetimerange' },
                  as: :string, start_year: Date.today.year %>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col">
      <%= m.input :duration, required: true,
                  input_html: { value: 60, min: 60, max: 1440, step: 5 } %>
    </div>
  </div>

  <%= m.button :submit, class: 'btn-primary' %>
<% end %>

app/views/meetings/show.html.erb
<h1><%= @meeting.title %></h1>

<% if @meeting.preview_image.attached? %>
  <div class="mt-4 mb-4">
    <%= image_tag @meeting.preview_image, style: 'max-width: 100%' %>
  </div>
<% end %>

<p><%= @meeting.description %></p>
<% if @meeting.participants_limit %>
  <%= content_tag :div, "#{t('participants_amount')}: #{@meeting.participants_limit}", class: 'mb-3' %>
<% end %>

<address>
  <b class="ymaps-geolink"><%= @meeting.address %></b>
</address>

<div>
  <%= time_tag @meeting.started_at %>
  &nbsp;-
  <%= time_tag @meeting.finished_at %>
</div>

app/views/partials/_notice.html.erb
<% unless text.to_s.empty? %>
  <% category ||= 'alert-primary' %>
  <div class="<%="alert notice #{category}"%>" role="alert">
    <%=text%>
  </div>
<% end %>

app/views/partials/_profile_links.html.erb
<%= content_tag :div, class: "float-end" do %>
  <%= content_tag :span, class: "me-3" do %>
    <%= link_to t("profile"), edit_user_path(current_user.id), class: "link-dark" %>
    <%= fa_icon "user" %>
  <% end %>

  <%= content_tag :span do %>
    <%= link_to t("auth.logout"), logout_path, class: "link-dark" %>
    <%= fa_icon "sign-out" %>
  <% end %>
<% end %>